{% set name = "tidy_headers" %}
{% set version = "1.0.2" %}
{% set sha256 = "152fe1e35046e10c2ffafdeba103e093edf91d721cb196e38c13964226da94ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
    - setuptools
    - pytest-runner
  run:
    - python
    - numpy

test:
  imports:
    - tidy_headers

about:
  home: https://github.com/untzag/tidy_headers
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Easy headers, inspired by the tidy data specification." 

extra:
  recipe-maintainers:
    - untzag
