travis:
  secure:
    BINSTAR_TOKEN: Q0frj6qS92TrT0TG+SwBiuMdkAkGSiuzcq6IHxnIlMoAF0xjNDAHOEhx8Bc/zklrdhSDkkRmWjdMPVYyULfCvpCegpP0zP61FuCZIHPd/qn+V8hRiYqg1DMfhmWtAbOq633BROOjEpW3uex7mm1SkvSr9d4ficXPW/0kwIiMg5DbXfCUdS0kGfieA2MBZBAFVdoIa/7nVHcIfttOQcKiYm4isTDSK43GKqTrnNETs2ZdV294RRKUc2EC1s9DAqB47BT+5MK4F5IR6PpXgQeNeL2ifVR6ll5HbVYrwzsm4318BuV4QGZNVDsXGd5Jj5mPwisEIhzvk8m8BLjIfDySpKgtfhYp6VhM+hbXHtEFL/ebW3bz1Kiu66s2RUKufkdJ7Z3rmEytGt0cB4R61kz9EOz/OI7E8kFQqS6R3jMCTJttADn6ddh7uMNavt56KpZOMEm0ymOsZUPTKz0/FyopSQfOyBYnj1Zr81EFYWMfhnKZFJmFHhNtwrRp9TuaAlRkYnmgsKUdiIKITqIM3rEbC14pXJi0q8OawDF9L8DaXOIAlkuvR8YIaSb31hTpFwBN9Y2mqnybvhL6wqgWv0+P/yjGDM51zR1e7VaeoOj8gvAwNNxI8kOumc/WRH6gtulIjomklGzRiGYTkXrfv83Fdp1LE+CF6nRVmFFhP5Kzi80=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
