travis:
  secure:
    BINSTAR_TOKEN: XUwWYdqnTTYjAzhenEloBgDDGz5DbWlA6T5KRda0gHwGwZW6P+Ck2p0bVSl2+UImsBTOW8kNLRL9gGRo0wevxeoaQKiJDwVPVnjUoiHJkCZrWnFyy+InEK4oqhD0VPqKuERDPfh98Npp+fGwyTV6l/b7MS8OblnwpZB7xiEGSnzHiB9MGQ9fJfoDDL/F4QhjFluTml25hAkbVIFGWqJ+aSPNuLoqNSb1/t07r1hp0dzdxCMak6nCLkQYS5bEAa3Na7T7eDcd2ZJOcWgCs8FB4HVIuoihnaowD3QDHeokTCs4OcCdMvjW/RnrN+hVl14RpeWGuYTNwaNpXwfCcoU77Ac2+hAfMnliZDudrjT+18+YX5MrtDkAnoV5Tx3nhGhNLAV4C/DT+XmYj5jMeRK+4p0ziODDHroVc+wF80nC52A0C0YPmr5sBQHwxPiuSHMzPsdrSnnxqAOlnFf01/YiIgvQpLMuZQpCcNtwQn4TvYQT5q2NnRxMG937rM+o31JWEUCaJ7yQC2XLSSxVlt/AiMhESyaALgNcPgaJpCDk8u9GD8EO99cFgSLaEPyQkebc0ZWkcqlf/FujrPpiVGwRvYE3N/x8ce1RnpSeEnRzYU82lmyAgBGy2Zgb4p8HdXynex6kEdEoS3UHmMeoGPK3z7LMXufBW7qosojpEo3zxBc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
